### ISSUE TITLE
How to insert the SEO tags inside the template

### ISSUE THREAD

**Issue by rgcarrasqueira** [bitmazk/cmsplugin-blog-seo-addons#1]
Hi! I'm trying to use your plugin at my website, but I could not find on your documentation how to put the correct tag to show the keywords anda meta description. Can you give a clue on how to do this?

Thanks

Rogério

**Comment by Tyrdall** [comment]
Hej @rgcarrasqueira This is a quite old and unsupported app, since we are not using cmsplugin-blog anymore.

Here's the template tag: https://github.com/bitmazk/cmsplugin-blog-seo-addons/blob/master/cmsplugin_blog_seo_addons/templatetags/seo_addons_tags.py#L17

Seems like it has to be used like:

```
{% load seo_addons_tags %}
{% get_entry_meta_description entry request %}
```

@dkaufhold right?

**Comment by dkaufhold** [comment]
Looks good to me.

@rgcarrasqueira Just keep in mind, that there's only the tag for description atm and it outputs only text, not the markup around it.
